env: prod
component: payment
params: "CART_HOST:prod.payment.cart_host,CART_PORT:prod.payment.cart_port,USER_HOST:user,USER_PORT:8080,AMQP_HOST:prod.payment.amqp_host,AMQP_USER:prod.rabbitmq.amqp_user,AMQP_PASS:prod.rabbitmq.amqp_pass"